services:
  backend:
    build:
      context: ./backend
    ports:
      - "5173:5173"
    environment:
      - PORT=5173

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
